# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be5ace1b305f0bcc69b8816b483bd47cebe34cc0eb607675b230701a7fb39d6d42a182fa540660c2f3fa5b903907b475f2761b8f7cddb0b0f300543b10a4da13

test:
  secret_key_base: f0890ec556b97c20ada04e9dbae644a6b59d425ced9dd6ff35f7f741537caea41c9deaa7dff6e1e4949b4631f3cc204da53fdef45050af3e0c7026020904c963

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
